### ISSUE TITLE
Not working for me on Android 5.0 :(

### ISSUE THREAD

**Issue by williams-sgvu** [pelotasplus/ActionAfterUninstall#1]
Hi there,

I tried to run your project in android studio. I did only one change in the local.properties that I added NDK location path of my system.

sdk.dir=C:\Android SDK\sdk
ndk.dir=C:\android-ndk-r10e

Rest everything is same. I tried to run project then application has installed successfully on my device but when I uninstall it then it doesn't open any website as per the code. Please help why this is weird for me :( . 

Here please see my below logs 

07-11 08:13:01.419      494-520/system_process I/ActivityManager﹕ Displayed pl.pelotasplus.actionafteruninstall/.MainActivity: +1s112ms (total +12s331ms)
07-11 08:13:02.052    4039-4039/pl.pelotasplus.actionafteruninstall I/Native﹕ Fork parent 4039
07-11 08:13:02.052    4069-4069/? I/Native﹕ Fork child
07-11 08:13:02.052    4069-4069/? I/Native﹕ My PID 4069
07-11 08:13:02.052    4069-4069/? I/Native﹕ fd=30
07-11 08:13:02.052    4069-4069/? I/Native﹕ Watching /data/data/pl.pelotasplus.actionafteruninstall
07-11 08:13:48.851        83-83/? D/Genyd﹕ Received Set Clipboard
07-11 08:13:48.851        83-83/? D/Genymotion﹕ Received Set Clipboard
07-11 08:18:02.691      494-553/system_process W/AudioTrack﹕ AUDIO_OUTPUT_FLAG_FAST denied by client
07-11 08:18:02.723      180-180/? E/EGL_emulation﹕ tid 180: eglCreateSyncKHR(1181): error 0x3004 (EGL_BAD_ATTRIBUTE)
07-11 08:18:02.939      494-553/system_process W/AudioTrack﹕ AUDIO_OUTPUT_FLAG_FAST denied by client
07-11 08:18:02.989     825-1070/com.android.launcher3 W/EGL_emulation﹕ eglSurfaceAttrib not implemented
07-11 08:18:02.989     825-1070/com.android.launcher3 W/OpenGLRenderer﹕ Failed to set EGL_SWAP_BEHAVIOR on surface 0x9f270220, error=EGL_SUCCESS
07-11 08:18:03.064      825-825/com.android.launcher3 W/ViewRootImpl﹕ Dropping event due to no window focus: KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x48, repeatCount=0, eventTime=1182212, downTime=1182212, deviceId=-1, source=0x101 }
07-11 08:18:06.158      825-825/com.android.launcher3 D/Launcher.Workspace﹕ 11683562 - addExtraEmptyScreenOnDrag()
07-11 08:18:06.158      825-825/com.android.launcher3 D/Launcher.Workspace﹕ 11683562 - insertNewWorkspaceScreen(): -201 at index: 1
07-11 08:18:07.649      494-838/system_process I/ActivityManager﹕ START u0 {act=android.intent.action.DELETE dat=package:pl.pelotasplus.actionafteruninstall flg=0x10800000 cmp=com.android.packageinstaller/.UninstallerActivity (has extras)} from uid 10039 on display 0
07-11 08:18:07.655      825-825/com.android.launcher3 D/Launcher.Workspace﹕ 11683562 - removeExtraEmptyScreen()
07-11 08:18:07.656      825-825/com.android.launcher3 D/Launcher.Workspace﹕ 11683562 - convertFinalScreenToEmptyScreenIfNecessary()
07-11 08:18:07.656      825-825/com.android.launcher3 D/Launcher.Workspace﹕ 11683562 - fadeAndRemoveEmptyScreen()
07-11 08:18:07.814    1841-1859/com.android.packageinstaller W/EGL_emulation﹕ eglSurfaceAttrib not implemented
07-11 08:18:07.814    1841-1859/com.android.packageinstaller W/OpenGLRenderer﹕ Failed to set EGL_SWAP_BEHAVIOR on surface 0xabb5fdc0, error=EGL_SUCCESS
07-11 08:18:07.850      825-825/com.android.launcher3 D/Launcher.Workspace﹕ 11683562 - stripEmptyScreens()
07-11 08:18:07.902    1841-1859/com.android.packageinstaller W/EGL_emulation﹕ eglSurfaceAttrib not implemented
07-11 08:18:07.902    1841-1859/com.android.packageinstaller W/OpenGLRenderer﹕ Failed to set EGL_SWAP_BEHAVIOR on surface 0xb0377b80, error=EGL_SUCCESS
07-11 08:18:08.003      825-825/com.android.launcher3 D/Launcher.Workspace﹕ 11683562 - stripEmptyScreens()
07-11 08:18:08.060      494-520/system_process I/ActivityManager﹕ Displayed com.android.packageinstaller/.UninstallerActivity: +349ms
07-11 08:18:09.318      494-553/system_process W/AudioTrack﹕ AUDIO_OUTPUT_FLAG_FAST denied by client

**Comment by pelotasplus** [comment]
yeah, it doesn't work on 5.0 and up and there is no fix for that
